# Form implementation generated from reading ui file 'D:\YL\my_coffee\UI\addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(300, 225)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddEditCoffeeForm.sizePolicy().hasHeightForWidth())
        AddEditCoffeeForm.setSizePolicy(sizePolicy)
        AddEditCoffeeForm.setMaximumSize(QtCore.QSize(400, 260))
        self.gridLayout = QtWidgets.QGridLayout(AddEditCoffeeForm)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.line_id = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.line_id.setReadOnly(True)
        self.line_id.setObjectName("line_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_id)
        self.label_2 = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.line_name = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.line_name.setObjectName("line_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_name)
        self.label_3 = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.combo_roasting = QtWidgets.QComboBox(parent=AddEditCoffeeForm)
        self.combo_roasting.setObjectName("combo_roasting")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.combo_roasting)
        self.label_4 = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.combo_ground = QtWidgets.QComboBox(parent=AddEditCoffeeForm)
        self.combo_ground.setObjectName("combo_ground")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.combo_ground)
        self.label_5 = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.combo_taste = QtWidgets.QComboBox(parent=AddEditCoffeeForm)
        self.combo_taste.setObjectName("combo_taste")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.combo_taste)
        self.label_6 = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.line_price = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.line_price.setObjectName("line_price")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_price)
        self.label_7 = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.line_volume = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.line_volume.setObjectName("line_volume")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_volume)
        self.button_execute = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.button_execute.setObjectName("button_execute")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.button_execute)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Dialog"))
        self.label.setText(_translate("AddEditCoffeeForm", "ID"))
        self.label_2.setText(_translate("AddEditCoffeeForm", "Название"))
        self.label_3.setText(_translate("AddEditCoffeeForm", "Обжарка"))
        self.label_4.setText(_translate("AddEditCoffeeForm", "Помол"))
        self.label_5.setText(_translate("AddEditCoffeeForm", "Вкус"))
        self.label_6.setText(_translate("AddEditCoffeeForm", "Цена, руб."))
        self.line_price.setPlaceholderText(_translate("AddEditCoffeeForm", "целое число"))
        self.label_7.setText(_translate("AddEditCoffeeForm", "Объем, гр"))
        self.line_volume.setPlaceholderText(_translate("AddEditCoffeeForm", "целое число"))
        self.button_execute.setText(_translate("AddEditCoffeeForm", "PushButton"))
